config/routes.rb
Rails.application.routes.draw do
  
  
  resources :test_papers

  mount Ckeditor::Engine => '/ckeditor'
  resources :test_attempts

  resources :teachers do
    resources :groups
  end

  resources :courses do
    resources :customized_concepts
    get 'concept_map'
    get 'concept_list'
    get 'list_students'
    get 'reports'
    get 'course_filter', on: :collection
    get 'filter_by_level', on: :collection
    get 'change_status/:group_id', to: 'courses#change_status', as: 'change_status'
  end

  resources :collect_courses do
    get 'join_list/:course_id', to: 'collect_courses#join_list', as: 'join_list', on: :collection
    get 'join_group/:group_id', to: 'collect_courses#join_group', as: 'join_group'
  end

  resources :groups do
    resources :courses
    post 'add_student', on: :collection
  end

  resources :prototypes do
    get 'landing_page', on: :collection
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  

  authenticated :user do
    root to: "prototypes#index", as: :authenticated_root
  end
  unauthenticated do
    root to: "prototypes#landing_page", as: :unauthenticated_root
  end
  
  get '/courses/12/' => 'prototype#course', as: :course1
  get '/courses/13/' => 'prototype#course2', as: :course2
  get '/courses/14/' => 'prototype#course3', as: :course3
  get '/test/12/' => 'prototype#test', as: :test
  get '/test/13/' => 'prototype#test2', as: :test2
  get '/test/14/' => 'prototype#test3', as: :test3
  get '/test/15/' => 'prototype#special_test', as: :special_test
  get '/test/12/result' => 'prototype#result', as: :result
  get '/test/13/result' => 'prototype#result2', as: :result2
  get '/test/14/result' => 'prototype#result3', as: :result3
  get '/rank' => 'prototype#rank', as: :rank
  get '/mission_center' => 'prototype#mission_center', as: :mission_center
  get '/mission_danger' => 'prototype#mission_danger', as: :mission_danger
  

  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    # omniauth_callbacks: "users/omniauth_callbacks",
    # confirmations: "users/confirmations",
    # passwords: "users/passwords"
  }

  devise_scope :user do
    get 'users/student_new', to: 'users/registrations#student_new', :as => :new_student_registration
    get 'users/teacher_new', to: 'users/registrations#teacher_new', :as => :new_teacher_registration
    # get 'users/student_edit', to: 'users/registrations#student_edit', :as => :edit_student_registration
    # get 'users/teacher_edit', to: 'users/registrations#teacher_edit', :as => :edit_teacher_registration
  end

  resources :customized_concepts do
    resources :tests
    resources :test_attempts
    resources :test_papers
    resources :test_paper_questions
    get 'student_detail/:user_id', to: 'customized_concepts#student_detail', as: 'student_detail'
    get 'paper_option', on: :collection
  end

  resources :test_paper_questions do
    get 'test_preview'
  end

  get 'build_by_database/:customized_concept_id', to: 'test_paper_questions#build_by_database', as: 'build_by_database'
  get 'search_test', to: 'test_paper_questions#search_test', as: 'search_test'
  get 'add_test/:customized_concept_id/:test_paper_question_id', to: 'test_paper_questions#add_test', as: 'add_test'
  
  resources :personal_profiles

  resources :collect_videos
  # FOR THE CITY SELECT FORM IN THE SINGUP PAGE 
  mount TaiwanCity::Engine => '/taiwan_city'
end

app/views/partials/_course_info.html.erb
  <div class="row">
    <div class="col-md-12">
      <% my_courses.each do |course| %>
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail" >
            <%= link_to(course_path(course)) do %>
              <h4 class="text-center"><span class="label label-info">Free Course</span></h4>
              <% if course.image_url %>
                <div class="course-image-wrapper">
                  <img src=<%= course.image.url %> class="img-responsive">
                </div>
              <% else %>
                <div class="course-image-wrapper">
                  <img src="http://placehold.it/650x450&text=Course name" class="img-responsive">
                </div>
              <% end %>

              <div class="caption">
                <div class="row">
                  <div class=".col-md-12 col-xs-12">
                    <h6><%= EducationLevel.find(course.education_level_id).title %> <%= Subject.find(course.subject_id).title %> <%=Volume.where(number: course.volume_id).first.title if Volume.where(number: course.volume_id).first%></h6>
                    <h5><%= course.title %></h5>
                  </div>
                </div>
                <p> </p>
                <div class="row">
                  <div class="col-md-6">
                    <!-- <a class="btn btn-primary btn-product"><span class="glyphicon glyphicon-thumbs-up"></span> Like</a>  -->
                  </div>
                  <div class="col-md-10">
                    <% if user_signed_in? %>
                      <% if current_user.has_role? :teacher  %>
                        <%= link_to join_list_collect_courses_path(course), remote: true, class: "btn btn-success btn-product" do %>
                          <span class="glyphicon glyphicon-shopping-cart"></span>收藏
                        <% end %>
                      <% else %>
                        <a href="#" class="btn btn-success btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> Buy</a>
                      <% end %>
                    <% else %>
                      <a href="#" class="btn btn-success btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> Buy</a>
                    <% end %>
                    
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div> 
      <% end %>  
    </div> 

    <%= paginate my_courses, :window => 2, :left => 1, :right => 3 %>
  </div>

app/views/partials/_courses_path.html.erb
<div class="courses-path-wrapper">
  <div class="courses-path-inner">
    <div class="courses-list-wrapper">
      <% @courses.each_with_index do |course, index| %>
        <div class="course-item">
          <div class="point">
            <%= render_course_status(course[:status]) %>
          </div>
          <div class="title">
            <h4>
              <%= link_to course[:path] do %>
                <%= course[:title] %>
              <% end %>
            </h4>
          </div>
          <div class="description">
            <h5>關卡描述</h5>
            <p><%= course[:description] %></p>
            <% if !course[:sub_titles].empty? %>
              <h5>子關卡</h5>
              <ul>
                <% course[:sub_titles].each do |sub_title| %>
                  <li><%= sub_title %></li>
                <% end %>
              </ul>
            <% end %>
            <h5>可獲得的經驗值</h5>
            <span><%= course[:exp] %></span> EXP
            <h5>可獲得的金幣</h5>
            <span><%= course[:money] %> 枚</span>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>


<ul> 
  <% @concepts.each do |concept| %>
    <li> <%= link_to(concept.title, concept_path(concept)) %> </li>
  <% end %>
</ul>

app/views/partials/_personal_avatar.html.erb
<div class="profile-sidebar">
  <!-- SIDEBAR USERPIC -->
  
  <!-- END SIDEBAR USERPIC -->
  <!-- SIDEBAR USER TITLE -->
  <% if current_user.has_role? :student %>
    <div class="profile-userpic">
    <% if user.avatar? %>
      <%= image_tag(user.avatar.thumb.url, class: "img-responsive")%>
    <% else %>
      <img src="http://keenthemes.com/preview/metronic/theme/assets/admin/pages/media/profile/profile_user.jpg" class="img-responsive" alt="">
    <% end %>
    </div>
    <div class="profile-usertitle">
      <div class="profile-usertitle-name">
        <%= user.username %>
      </div>
      <div class="profile-usertitle-job">
        學校：<%= user.school %>
      </div>
      <div class="profile-usertitle-job">
        P幣：<%= user.point if user.point%>
      </div>
    </div>
    <!-- END SIDEBAR USER TITLE -->
    <!-- SIDEBAR MENU -->
    <div class="profile-usermenu">
      <ul class="nav">
        <li>
          <a href="#">
          <i class="glyphicon glyphicon-user"></i>
          Account Settings </a>
        </li>
        <li>
          <a href="#">
          <i class="glyphicon glyphicon-flag"></i>
          Help </a>
        </li>
      </ul>
    </div>
    <!-- END MENU -->
  <% else %>
    <div class="profile-userpic">
      <% if user.avatar? %>
        <%= image_tag(user.avatar.thumb.url, class: "img-responsive") %>
      <% else %>
        <img src="http://keenthemes.com/preview/metronic/theme/assets/admin/pages/media/profile/profile_user.jpg" class="img-responsive" alt="">
      <% end %>
    </div>
    <div class="profile-usertitle">
      <div class="profile-usertitle-name">
        <%= user.username %>
      </div>
      <div class="profile-usertitle-job">
        教授科目：<%= user.suject %>
      </div>
      <div class="profile-usertitle-job">
        服務單位：<%= user.service_unit %>
      </div>
    </div>
    <!-- END SIDEBAR USER TITLE -->
    <!-- SIDEBAR MENU -->
    <div class="profile-usermenu">
      <ul class="nav">
        <li>
          <a href="#">
          <i class="fa fa-user"></i></i>
          Account Settings </a>
        </li>
        <li>
          <%= link_to(new_teacher_group_path(user.id)) do %> 
           <i class="fa fa-users"></i></i> 建立群組
          <% end %>
        </li>
        <li>
          <a href="#">
          <i class="glyphicon glyphicon-flag"></i>
          Help </a>
        </li>
      </ul>
    </div>
    <!-- END MENU -->
  <% end %>
</div>

app/views/partials/_personal_info.html.erb
<div class="personal-info-wrapper">

  <% if current_user.has_role? :student %>
  <!-- student info -->
    <%= render partial: "partials/personal_avatar", locals: {user: @user} %>
    <%= form_tag("/groups/add_student", method: "post") do %>
      <%= text_field_tag(:group_id) %>
      <%= submit_tag("加入群組") %>
    <% end %>

    <div class="list-group">
      <li class="list-group-item active"><strong>群組</strong></li>
      <% @groups.each do |group| %>
        <li class="list-group-item"><span class="badge">9</span><%= link_to("#{group.name}", group_path(group)) %></li>
      <% end %>
    </div>

    <ul class="list-group">
      <li class="list-group-item list-group-item-warning"><strong>學程</strong></li>
      <% @target_courses.each do |t| %>
      <li class="list-group-item"> <%= radio_button_tag(:education_level_id, t.id, false, data: {remote: true, url: filter_by_level_courses_path}) %> <%= t.title %></li>
      <% end %>
    </ul>

    <ul class="list-group subject-list">
      
    </ul>
    
  <% else %>
    <!-- Teacher info   -->
    <%= render partial: "partials/personal_avatar", locals: {user: @user} %>
    <!-- END Teach info -->
    <br>
    
    <!-- list all group -->
    <div class="list-group">
      <li class="list-group-item active"><strong>群組</strong></li>
      <% @groups.each do |group| %>
        <li class="list-group-item"><%= link_to(group.name, teacher_group_path(@user, group.id)) %></li>
      <% end %>
    </div>
    <!-- list all subject -->

    <ul class="list-group">
      <li class="list-group-item list-group-item-warning"><strong>學程</strong></li>
      <% @target_courses.each do |t| %>
      <li class="list-group-item"> <%= radio_button_tag(:education_level_id, t.id, false, data: {remote: true, url: filter_by_level_courses_path}) %> <%= t.title %></li>
      <% end %>
    </ul>

    <ul class="list-group subject-list">
      
    </ul>
  <% end %>

</div>

app/views/partials/_personal_skill_list.html.erb
<h3 class="personal-skill-list-title">技能列表</h3>
<div class="personal-skill-list-content-wrapper">
  <% @skills.each do |skill| %>
    <section>
      <h4><%= skill[:title] %></h4>
      <ul>
        <% skill[:learned].each do |item| %>
        <li><%= item %></li>
        <% end %>
      </ul>
    </section>
  <% end %>
</div>