config/routes.rb
Rails.application.routes.draw do
  
  
  resources :test_papers

  mount Ckeditor::Engine => '/ckeditor'
  resources :test_attempts

  resources :teachers do
    resources :groups
  end

  resources :courses do
    resources :customized_concepts
    get 'concept_map'
    get 'concept_list'
    get 'list_students'
    get 'reports'
    get 'course_filter', on: :collection
    get 'filter_by_level', on: :collection
    get 'change_status/:group_id', to: 'courses#change_status', as: 'change_status'
  end

  resources :collect_courses do
    get 'join_list/:course_id', to: 'collect_courses#join_list', as: 'join_list', on: :collection
    get 'join_group/:group_id', to: 'collect_courses#join_group', as: 'join_group'
  end

  resources :groups do
    resources :courses
    post 'add_student', on: :collection
  end

  resources :prototypes do
    get 'landing_page', on: :collection
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  

  authenticated :user do
    root to: "prototypes#index", as: :authenticated_root
  end
  unauthenticated do
    root to: "prototypes#landing_page", as: :unauthenticated_root
  end
  
  get '/courses/12/' => 'prototype#course', as: :course1
  get '/courses/13/' => 'prototype#course2', as: :course2
  get '/courses/14/' => 'prototype#course3', as: :course3
  get '/test/12/' => 'prototype#test', as: :test
  get '/test/13/' => 'prototype#test2', as: :test2
  get '/test/14/' => 'prototype#test3', as: :test3
  get '/test/15/' => 'prototype#special_test', as: :special_test
  get '/test/12/result' => 'prototype#result', as: :result
  get '/test/13/result' => 'prototype#result2', as: :result2
  get '/test/14/result' => 'prototype#result3', as: :result3
  get '/rank' => 'prototype#rank', as: :rank
  get '/mission_center' => 'prototype#mission_center', as: :mission_center
  get '/mission_danger' => 'prototype#mission_danger', as: :mission_danger
  

  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    # omniauth_callbacks: "users/omniauth_callbacks",
    # confirmations: "users/confirmations",
    # passwords: "users/passwords"
  }

  devise_scope :user do
    get 'users/student_new', to: 'users/registrations#student_new', :as => :new_student_registration
    get 'users/teacher_new', to: 'users/registrations#teacher_new', :as => :new_teacher_registration
    # get 'users/student_edit', to: 'users/registrations#student_edit', :as => :edit_student_registration
    # get 'users/teacher_edit', to: 'users/registrations#teacher_edit', :as => :edit_teacher_registration
  end

  resources :customized_concepts do
    resources :tests
    resources :test_attempts
    resources :test_papers
    resources :test_paper_questions
    get 'student_detail/:user_id', to: 'customized_concepts#student_detail', as: 'student_detail'
    get 'paper_option', on: :collection
  end

  resources :test_paper_questions do
    get 'test_preview'
  end

  get 'build_by_database/:customized_concept_id', to: 'test_paper_questions#build_by_database', as: 'build_by_database'
  get 'search_test', to: 'test_paper_questions#search_test', as: 'search_test'
  get 'add_test/:customized_concept_id/:test_paper_question_id', to: 'test_paper_questions#add_test', as: 'add_test'
  
  resources :personal_profiles

  resources :collect_videos
  # FOR THE CITY SELECT FORM IN THE SINGUP PAGE 
  mount TaiwanCity::Engine => '/taiwan_city'
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :teacher

  has_many :courses, :dependent => :destroy
  
  has_many :student_groupships
  has_many :students, :through => :student_groupships
  validates :group_code, :presence => true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    if current_user.has_role? :student
      @group = Group.find(params[:id])
      @courses = @group.courses.order(:title).page params[:page]
      @students = @group.students
    end

    if current_user.has_role? :teacher
      @teacher = Teacher.find(params[:teacher_id])
      @group = @teacher.groups.find(params[:id])
      @courses = @group.courses.order(:title).page params[:page]
      @students = @group.students
    end
  end

  # GET /groups/new
  def new
    @teacher = Teacher.find(params[:teacher_id])
    @group = @teacher.groups.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @teacher = Teacher.find(params[:teacher_id])
    @group = @teacher.groups.new(group_params)

    @group.group_code = SecureRandom.hex(2)
    respond_to do |format|
      if @group.save
        format.html { redirect_to teacher_group_path(@teacher, @group), notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_student
    @group = Group.where(group_code: params[:group_id])
  
    if @group.count != 0
      @student_group = @group.first.student_groupships.create
      @student_group.student = current_user.student
      @student_group.save
      redirect_to authenticated_root_path

    else
      redirect_to authenticated_root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      # @group = Group.find(params[:id])
      # @courses = @group.courses
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:teacher_id, :name, :group_code)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="pb-index-wrapper pb-container">
  <%= simple_form_for([@teacher, @group]) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/groups/_group_course_info.html.erb
<div class="row">
  <div class="col-md-12">
    <% my_courses.each do |course| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail" >
          <%= link_to(group_course_path(group, course)) do %>
            <h4 class="text-center"><span class="label label-info">Free Course</span></h4>
            <% if course.image_url %>
              <div class="course-image-wrapper">
                <img src=<%= course.image.url %> class="img-responsive">
              </div>
            <% else %>
              <div class="course-image-wrapper">
                <img src="http://placehold.it/650x450&text=Course name" class="img-responsive">
              </div>
            <% end %>

            <div class="caption">
              <div class="row">
                <div class=".col-md-12 col-xs-12">
                  <h6><%= EducationLevel.find(course.education_level_id).title %> <%= Subject.find(course.subject_id).title %> <%=Volume.where(number: course.volume_id).first.title if Volume.where(number: course.volume_id).first%></h6>
                  <h5><%= course.title %></h5>
                </div>
              </div>
              <p> </p>
              <div class="row">
                <div class="col-md-6">
                  <!-- <a class="btn btn-primary btn-product"><span class="glyphicon glyphicon-thumbs-up"></span> Like</a>  -->
                </div>
                <div class="col-md-6">
                  <!-- <a href="#" class="btn btn-success btn-product"><span class="glyphicon glyphicon-shopping-cart"></span> Buy</a> -->
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div> 
    <% end %>  
  </div> 

  <%= paginate my_courses, :window => 2, :left => 1, :right => 3 %>
</div>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th>Teacher</th>
      <th>Name</th>
      <th>Group code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.teacher_id %></td>
        <td><%= group.name %></td>
        <td><%= group.group_code %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<div class="pb-index-wrapper pb-container">
  <!-- Back Link -->
  <div class="row">
    <div class="col-md-2">
      <%=link_to authenticated_root_path do %> 
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> 教師首頁
      <% end %>
    </div>
  </div>
  <!-- End Back Link -->
  
  <div class="col-md-offset-5 col-md-4">
    <h1>建立群組</h1>  
  </div>
  <br>
  <%= render 'form' %>

</div>

app/views/groups/show.html.erb
<div class="pb-index-wrapper pb-container">
  <!-- Back Link -->
  <% if current_user.has_role? :student %>
    <%=link_to authenticated_root_path do %> 
      <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> 學生首頁
    <% end %>
  <% else %>
    <%=link_to authenticated_root_path do %> 
      <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> 教師首頁
    <% end %>
  <% end %>
  <!-- End Back Link -->
  
  <div class="row">
    <!-- RIGHT PAGE -->
    <div class="col-md-9 col-md-push-3">
      <%= render partial: "groups/group_course_info", locals: {my_courses: @courses, group: @group} if @courses%>
    </div>
    <!-- END RIGHT PAGE -->

    <!-- LEFT PAGE -->
    <div class="col-md-3 col-md-pull-9">
      <% if current_user.has_role? :student %>
        <p id="notice"><%= notice %></p>
        <h2><%= Teacher.find(@group.teacher_id).username %>老師的群組</h2>
        <h3>建立者：<%= @group.name %></h3>
      <% else %>
        <p id="notice"><%= notice %></p>
        <h2><%= Teacher.find(@group.teacher_id).username %>老師</h2>
        <h3><%= @group.name %></h3>
        <p>
          <strong>Group code:</strong>
          <%= @group.group_code %>
        </p>
        <p><%=link_to("建立課程",new_group_course_path(@group), class: "btn btn-default") %></p>
        <p><%= link_to("課程編輯", group_courses_path(@group), class: "btn btn-default") %></p>
      <% end %>

      
      <div class="list-group">
        <a href="#" class="list-group-item active">
          群組成員
        </a>
        <% @students.each do |student| %>
        <a href="#" class="list-group-item"><%= student.username %></a>
  
        <% end %>
      </div>
    </div>
    <!-- END LEFT PAGE -->
  </div>

</div>


<!-- Modal : WHEN USER CREATE GROUP SUCCESS -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">成功建立"<%= @group.name %>群組"，群組代碼為：<%= @group.group_code %></h4>
      </div>
      <div class="modal-body">
        <p>學生輸入代碼加入您的群組後，您即可掌握每一位學生的學習狀況。</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">我了解</button>
      </div>
    </div>
  </div>
</div>
<!-- END Modal -->
<script src="https://code.jquery.com/jquery-1.10.2.js"></script>

<script>  
  $(document).ready(function() {
    if($("#notice").html().indexOf("Group was successfully created") >= 0) {
      $('#myModal').modal();
    }
  });
</script>