config/routes.rb
Rails.application.routes.draw do
  
  
  resources :test_papers

  mount Ckeditor::Engine => '/ckeditor'
  resources :test_attempts

  resources :teachers do
    resources :groups
  end

  resources :courses do
    resources :customized_concepts
    get 'concept_map'
    get 'concept_list'
    get 'list_students'
    get 'reports'
    get 'course_filter', on: :collection
    get 'filter_by_level', on: :collection
    get 'change_status/:group_id', to: 'courses#change_status', as: 'change_status'
  end

  resources :collect_courses do
    get 'join_list/:course_id', to: 'collect_courses#join_list', as: 'join_list', on: :collection
    get 'join_group/:group_id', to: 'collect_courses#join_group', as: 'join_group'
  end

  resources :groups do
    resources :courses
    post 'add_student', on: :collection
  end

  resources :prototypes do
    get 'landing_page', on: :collection
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  

  authenticated :user do
    root to: "prototypes#index", as: :authenticated_root
  end
  unauthenticated do
    root to: "prototypes#landing_page", as: :unauthenticated_root
  end
  
  get '/courses/12/' => 'prototype#course', as: :course1
  get '/courses/13/' => 'prototype#course2', as: :course2
  get '/courses/14/' => 'prototype#course3', as: :course3
  get '/test/12/' => 'prototype#test', as: :test
  get '/test/13/' => 'prototype#test2', as: :test2
  get '/test/14/' => 'prototype#test3', as: :test3
  get '/test/15/' => 'prototype#special_test', as: :special_test
  get '/test/12/result' => 'prototype#result', as: :result
  get '/test/13/result' => 'prototype#result2', as: :result2
  get '/test/14/result' => 'prototype#result3', as: :result3
  get '/rank' => 'prototype#rank', as: :rank
  get '/mission_center' => 'prototype#mission_center', as: :mission_center
  get '/mission_danger' => 'prototype#mission_danger', as: :mission_danger
  

  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    # omniauth_callbacks: "users/omniauth_callbacks",
    # confirmations: "users/confirmations",
    # passwords: "users/passwords"
  }

  devise_scope :user do
    get 'users/student_new', to: 'users/registrations#student_new', :as => :new_student_registration
    get 'users/teacher_new', to: 'users/registrations#teacher_new', :as => :new_teacher_registration
    # get 'users/student_edit', to: 'users/registrations#student_edit', :as => :edit_student_registration
    # get 'users/teacher_edit', to: 'users/registrations#teacher_edit', :as => :edit_teacher_registration
  end

  resources :customized_concepts do
    resources :tests
    resources :test_attempts
    resources :test_papers
    resources :test_paper_questions
    get 'student_detail/:user_id', to: 'customized_concepts#student_detail', as: 'student_detail'
    get 'paper_option', on: :collection
  end

  resources :test_paper_questions do
    get 'test_preview'
  end

  get 'build_by_database/:customized_concept_id', to: 'test_paper_questions#build_by_database', as: 'build_by_database'
  get 'search_test', to: 'test_paper_questions#search_test', as: 'search_test'
  get 'add_test/:customized_concept_id/:test_paper_question_id', to: 'test_paper_questions#add_test', as: 'add_test'
  
  resources :personal_profiles

  resources :collect_videos
  # FOR THE CITY SELECT FORM IN THE SINGUP PAGE 
  mount TaiwanCity::Engine => '/taiwan_city'
end

app/models/customized_concept.rb
class CustomizedConcept < ActiveRecord::Base
  belongs_to :course
  has_many :tests, :dependent => :destroy
  accepts_nested_attributes_for :tests, :reject_if => lambda { |a| a[:question].blank? }

  has_many :test_paper_questions, :dependent => :destroy
  accepts_nested_attributes_for :test_paper_questions, :reject_if => lambda { |a| a[:question].blank? }
  
  
  has_many :test_attempts, :dependent => :destroy
  has_many :test_papers, :dependent => :destroy

  mount_uploader :lecture, LectureUploader
  paginates_per 1

  def next(course_id)
    self.class.where("id > ? AND course_id = ?", id, course_id).first
  end

  def previous(course_id)
    self.class.where("id < ? AND course_id = ?", id, course_id).last
  end

end

app/controllers/customized_concepts_controller.rb
class CustomizedConceptsController < ApplicationController
  before_action :set_customized_concept, only: [:show, :edit, :update, :destroy]

  # GET /customized_concepts
  # GET /customized_concepts.json
  def index
    @course = Course.find(params[:course_id])
    @customized_concepts = @course.customized_concepts

    respond_to do |format|
      format.html
      format.js
    end  
  end

  # GET /customized_concepts/1
  # GET /customized_concepts/1.json
  def show
    @course = Course.find(params[:course_id])
    @customized_concepts = @course.customized_concepts
    @customized_concept ||= CustomizedConcept.find(params[:id])
    @next_concept = @customized_concept.next(@course.id)
    @prev_concept = @customized_concept.previous(@course.id)

    @group = Group.find(params[:group_id]) if params[:group_id]

    @collect_video = current_user.collect_videos.build
  end

  # GET /customized_concepts/new
  def new
    @course = Course.find(params[:course_id])
    @customized_concept = @course.customized_concepts.new
    @database_tests = TestPaperQuestion.all # TO-DO :  like @chapter.test

    @chapters = Subject.find(@course.subject_id).chapters 
    @collect_videos = current_user.collect_videos
    respond_to do |format|
      format.js
    end
  end

  # GET /customized_concepts/1/editg
  def edit
    @course = Course.find(params[:course_id])
    @customized_concept = @course.customized_concepts.find(params[:id])
    @collect_videos = current_user.collect_videos

    respond_to do |format|
      format.js
    end
  end

  # POST /customized_concepts
  # POST /customized_concepts.json
  def create
    @course = Course.find(params[:course_id])
    @customized_concept = @course.customized_concepts.new(customized_concept_params)
    respond_to do |format|
      if @customized_concept.save
        format.html { redirect_to group_course_path(@course.group, @course), notice: 'Customized concept was successfully created.' }
        # format.json { render :show, status: :created, location: @customized_concept }
      else
        format.html { render :new }
        format.json { render json: @customized_concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customized_concepts/1
  # PATCH/PUT /customized_concepts/1.json
  def update
    @course = Course.find(params[:course_id])
    @customized_concept = CustomizedConcept.find(params[:id])
    if !params[:customized_concept][:test_paper_questions_attributes].blank?
      update_test_paper_option(params[:customized_concept][:test_paper_questions_attributes])
    end
    # remove the test_paper_options
    respond_to do |format|
      if @customized_concept.update!(customized_concept_params)
        format.html { redirect_to group_course_path(@course.group, @course), notice: 'Customized concept was successfully updated.' }
        format.json { render :show, status: :ok, location: @customized_concept }
      else
        format.html { render :edit }
        format.json { render json: @customized_concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customized_concepts/1
  # DELETE /customized_concepts/1.json
  def destroy
    @course = Course.find(params[:course_id])
    @customized_concept.destroy
    respond_to do |format|
      format.html { redirect_to group_course_path(@course.group, @course), notice: 'Customized concept was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def student_detail
    # for test attempt
    @concept = CustomizedConcept.find(params[:customized_concept_id])
    @tests = @concept.tests
    @test_attempts = @concept.test_attempts.where(user: params[:user_id], customized_concept_id: @concept.id)

    # for test paper
    @test_paper = @concept.test_papers.last
    @test_paper_question = @concept.test_paper_questions.last
    @test_paper_options = @test_paper_question.test_paper_options
  
  end

  def paper_option
    respond_to do |format|
      format.js
    end
  end

  def update_test_paper_option(questions_attributes)
    if questions_attributes[:"0"] != nil
      test_paper_options_attributes = questions_attributes[:"0"][:test_paper_options_attributes] 
      test_paper_options_attributes.each_value do |v| # only edit, but will get wrong when new;
        if v[:id]
          t = TestPaperOption.find(v[:id].to_i)
          t.answer = v[:answer]
          t.save!
          if v[:_destroy] == "1"
            t.destroy!
          end
        else
          t = @customized_concept.test_paper_questions.first.test_paper_options.new(answer: v[:answer], question_number: v[:question_number])
          t.save!
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customized_concept
      @customized_concept = CustomizedConcept.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customized_concept_params
      params.require(:customized_concept).permit(:course_id, 
                                                :title, 
                                                :description,
                                                :video,
                                                :lecture,
                                                tests_attributes: [:id,
                                                                   :question,
                                                                   :tip,
                                                                   :_destroy,
                                                                   :related_video,
                                                                   options_attributes: [:id, 
                                                                                        :description, 
                                                                                        :is_answer]
                                                                   ],
                                                test_paper_questions_attributes: [
                                                                    :id,
                                                                    :question,
                                                                    :customized_concept_id,
                                                                    test_paper_options_attributes: [:id, :answer, :test_paper_question_id, :question_number]
                                                                  ])
    end

end

app/helpers/customized_concepts_helper.rb
module CustomizedConceptsHelper

  def show_video_or_not(concept)
    if !concept.video.blank?
      content_tag(:div, class: "course-video-wrapper") do
        youtube_embed(concept.video)
      end
    end
  end

  def show_collect_video_button(concept)
    if current_user.collect_videos.find_by_url(concept.video).blank? && !concept.video.blank?
      content_tag(:button, "收藏影片", class: "btn btn-primary", "data-toggle" => "modal", "data-target" => ".collect_video_modal")
    else
      if !concept.video.blank?
        content_tag(:button, "已收藏", class: "btn btn-default", disabled: "disabled")  
      end  
    end
  end

end

app/views/customized_concepts/_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= simple_form_for([@course, @customized_concept]) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <div class="form-group">
        <%= f.input :title %> 
        </div>
        <%= f.input :description, class: "fa fa-user"%>
        <%= f.input :video %>
        

        <% if @test_paper_questions %>
          <%= f.fields_for :test_paper_questions do |test| %>
            <%= render 'test_paper_question_fields', :f => test %>
          <% end %>
        <% end %>

        <% if @tests %>
          <%= f.fields_for :tests do |test| %>
            <%= render 'test_fields', :f => test %>
          <% end %>
        <% end %>
        
        <% if @test_paper_questions.blank? && @tests.blank? %>
          <p><%= link_to_add_fields "自定考題", f, :tests, "btn btn-primary add_new_test", "Add a new Test" %> 
            <%= link_to_add_fields "上傳考題", f, :test_paper_questions, "btn btn-primary add_paper_test", "Add a new Test" %>
          </p>
        <% end %>

        <% if !@database_tests.blank? %>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">題庫出題</button>
        <% end %>

        <% if !@tests.blank? %>
          <p><%= link_to_add_fields "自定考題", f, :tests, "btn btn-primary add_new_test", "Add a new Test" %> </p>
        <% end %>
      </div>

      <% if !@customized_concept.lecture.blank? %>
        <%= f.input :lecture, as: :file, label: "已上傳講義 : #{@customized_concept.lecture_identifier}", wrapper_html: {class: "carrier-wave-field"}%>
      <% else %>
        <%= f.input :lecture, as: :file%>
      <% end %>
      

        
      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    <% end %>   

  </div>
</div>



<!-- Large modal -->


<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <% if !@database_tests.blank? %>
        <% @database_tests.each do |t| %>
          <li><%= t.id %> <%=t.tag_list %></li>
        <% end %>
      <% end %>
    </div>
  </div>
</div>


<script>
    function add_fields(link, association, content) {  
        var new_id = new Date().getTime();  
        var regexp = new RegExp("new_" + association, "g");  
        $(link).parent().before(content.replace(regexp, new_id));  
    }
    function remove_fields(link) {  
        $(link).prev("input[type=hidden]").val("1");  
        $(link).parent(".fields").slideUp();
    } 

    
</script>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>


<!-- it cover carrierwave's message : No file chosen -->
<script type="text/javascript">  
  $(document).ready(function () {
     $("input[type=file]").change(function(){
      $(this).parent().removeClass("arrier-wave-field").addClass("carrier-wave-field-uploaded");
     });
  });
</script>

app/views/customized_concepts/_index.html.erb
<p id="notice"><%= notice %></p>



<div class="courses-path-wrapper">
  <div class="courses-path-inner">
    <div class="courses-list-wrapper">
      <% @customized_concepts.each_with_index do |course, index| %>
        <div class="course-item">
          <div class="point">
            <%= render_course_status(course[:status]) %>
          </div>
          <div class="title">
            <h4>
              <%= link_to course_customized_concept_path(@course, course) do %>
                <%= course[:title] %>
              <% end %>
            </h4>
          </div>
          <div class="description"> 
            <h5>課程描述</h5>
            <p><%= course[:description] %></p>
           
              <h5>子關卡</h5>
              <ul>
                <li> test </li>
              </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/customized_concepts/_lecture_partial.html.erb
<% if concept.video.blank? %>
  <% if !concept.lecture.blank? %>
    <div class="col-md-10">
      <iframe src=<%= concept.lecture.url %> width="900" height="780" style="border: none;"> </iframe>
    </div>
  <% end %>
<% else %>
  <div class="button-wrapper">
    <%= link_to("顯示講義", concept.lecture.url, class: "course-btn") if concept.lecture? %>
  </div>
<% end %>

app/views/customized_concepts/_new_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= simple_form_for([@course, @customized_concept]) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <div class="form-group">
        <%= f.input :title, label: '觀念名稱' %> 
        </div>
        <%= f.input :description, label: '觀念描述' %>  
          
        <button type="button" class="btn btn-default" id="sellect-video-list"><i class="fa fa-youtube"></i></button>
        <%= f.input :video, label: '觀念相關影片連結', placeholder: 'http://..' %>

      </div>
      <div class="video-list"> 
        <div class="list-group">
          <% @collect_videos.each do |v| %>
            <button type="button" class="list-group-item"><%= v.title %> <div class="video-url"> <%= v.url %><div></button>
          <% end %>
        </div>
      </div>
      <% if !@customized_concept.lecture.blank? %>
        <%= f.input :lecture, as: :file, label: "已上傳講義 : #{@customized_concept.lecture_identifier}", wrapper_html: {class: "carrier-wave-field"}%>
      <% else %>
        <%= f.input :lecture, label: '講義', as: :file%>
      <% end %>
      

        
      <%= f.button :submit, "新增", class: "btn btn-primary" %>
    <% end %>   

  </div>
</div>



<script>
    function add_fields(link, association, content) {  
        var new_id = new Date().getTime();  
        var regexp = new RegExp("new_" + association, "g");  
        $(link).parent().before(content.replace(regexp, new_id));  
    }
    function remove_fields(link) {  
        $(link).prev("input[type=hidden]").val("1");  
        $(link).parent(".fields").slideUp();
    }
</script>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>


<!-- it cover carrierwave's message : No file chosen -->
<script type="text/javascript">  
  $(document).ready(function () {
     $("input[type=file]").change(function(){
      $(this).parent().removeClass("arrier-wave-field").addClass("carrier-wave-field-uploaded");
     });
  });
</script>

<script>
  $(document).ready(function () {
     $(".video-list").hide();
     $(".video-url").hide();

    $("#sellect-video-list").click(function(){
      $(".video-list").slideDown();
    });

    $(".list-group-item").click(function(){
      $("input[name*='customized_concept[video]'").val($(this).children('.video-url').text());
      $(".video-list").hide();
    });
  });
</script>

app/views/customized_concepts/_option_fields.html.erb
<div class="fields">
  <%= f.label :description, "Answer" %>
  <%= f.text_field :description %>
  <%= f.input :is_answer, inline_label: '勾選為正確答案'%>
  <%= f.hidden_field :_destroy %>  
  <%= link_to_remove_fields "remove", f %><br /> 
</div>

app/views/customized_concepts/_option_list.html.erb
<p> 請輸入各題答案 </p>

app/views/customized_concepts/_test_attemp_detail.html.erb
<div class="col-md-9 col-md-push-3">
      

  <table class="table table-striped table-hover">
    <thead>
      <h1> <%= @concept.title%> </h1>
      <p><i class="fa fa-calendar"></i> 測驗日期 : <%= @test_attempts.last.created_at.strftime("%Y/%m/%d") %></p>
      <p><i class="fa fa-clock-o"></i> 測驗時間 : <%= Time.at(@test_attempts.last.test_time_sec).utc.strftime("%H:%M:%S") if @test_attempts.last.test_time_sec%></p>
      <tr>
        <th>題目</th>
        <th>錯誤次數 </th>
        <th>時間</th>
      </tr>
    </thead>

    <tbody>
      <% @tests.each do |test| %>
      <tr>
        <td><%= raw(test.question)%></td>
        <td><%= @test_attempts.last.answer_records.where(test: test).first.error_times %></td>
        <td><%= @test_attempts.last.updated_at %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
 
  
</div>

<div class="col-md-3 col-md-pull-9">
  <div class="list-group">
    
  </div>
</div>

app/views/customized_concepts/_test_modal.html.erb
<div class="modal fade test-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">勾選題目</h4>
      </div>
      <div class="modal-body">
        <% database_tests.each do |t| %>
        <div class="row">
          <div class="jumbotron">
            <h3><%= t.question %></h3>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">Add</a></p>
          </div>
        </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/customized_concepts/_test_paper_detail.html.erb
<div class="col-md-7">
  <iframe src=<%= @concept.test_paper_questions.first.question.url %> width="800" height="780" style="border: none;"> </iframe>
</div>

<div class="col-md-4 pull-right">
  <table class="table table-striped table-hover">
    <thead>
      <h3> <%= @concept.title%> </h3>
      <p><i class="fa fa-calendar"></i> 測驗日期 : <%= @test_paper.created_at.strftime("%Y/%m/%d") %></p>
      <p><i class="fa fa-clock-o"></i> 測驗時間 : <%= Time.at(@test_paper.test_time_sec).utc.strftime("%H:%M:%S") if @test_paper.test_time_sec %></p>
      <tr>
        <th>題號</th>
        <th>錯誤次數 </th>
        <th>是否跳過</th>
        <th>正確答案</th>
        <th>作答記錄</th>
      </tr>
    </thead>

    <tbody>
      <% @test_paper.paper_answer_records.each do |record| %>
      <tr>
        <td><%= record.test %></td>
        <td><%= record.error_times %></td>
        <td><%= record.is_skip %></td>
        <td><%= number_to_letter(@test_paper_options.find_by_question_number(record.test).answer) %></td>
        

        <td> <%= list_answer_record(record) %> </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>


<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<script>
  $(document).on('ready', function(event) {
    $('[data-toggle="popover-record"]').popover()
  });
    // $('#report td:even').css({ backgroundColor: "#5cb85c", color: "white" });
</script>

app/views/customized_concepts/_test_paper_option_fields.html.erb
<div class="fields">
  <p class="options"> 
    <div class="checkbox">
    <%= f.collection_radio_buttons(:answer, SelectOption.all, :number, :label) do |b|%>
        <%= b.label() { b.radio_button+b.text } %>
    <% end %>
    </div>
  </p>
  <%= f.input :question_number, as: :hidden %>
  <%= f.hidden_field :_destroy %>  
  <%= link_to_remove_fields "remove", f %><br /> 


</div>

app/views/customized_concepts/new.html.erb
<div class="pb-index-wrapper pb-container">
  <div class="col-md-offset-5 col-md-4">
    <h1>新增觀念</h1>
  </div>
  <%= render 'form' %>

</div>

app/views/customized_concepts/new.js.erb
$('.concept-new-form').html('<%= escape_javascript render "new_form" %>');

app/views/customized_concepts/show.html.erb
<div class="pb-course-wrapper pb-container"> 

  <div class="row">
    <div class="col-md-9 col-md-push-3">
      <%= show_video_or_not(@customized_concept) %>
      <%= show_collect_video_button(@customized_concept) %>
      <nav>
        <ul class="pager">
          <li><%= link_to("上一個觀念", course_customized_concept_path(@course, @prev_concept)) if @prev_concept%></li>
          <li><%= link_to("下一個觀念", course_customized_concept_path(@course, @next_concept)) if @next_concept%></li>
        </ul>
      </nav>
      <div class="course-options">
        <%= render partial: "lecture_partial", locals: {concept: @customized_concept} %>
        <div class="button-wrapper">
          <%= link_to("開始自我挑戰", new_customized_concept_test_attempt_path(@customized_concept), class: "course-btn") if @customized_concept.tests.count != 0 %>
        </div>
        <div class="button-wrapper">
          <%= link_to("開始自我挑戰", new_customized_concept_test_paper_path(@customized_concept), class: "course-btn") if @customized_concept.test_paper_questions.count != 0 %>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-md-pull-9">
      <p id="notice"><%= notice %></p>
      
      <% if @group %>
        <%=link_to group_course_path(@group, @course) do %> 
          <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> 課程首頁
        <% end %>
      <% else %>
        <%=link_to course_path(@course) do %> 
          <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> 課程首頁
        <% end %>
      <% end %>

      <h2 class="course-title">
        <%= @customized_concept.title %>
      </h2>

      <h4>
        <%= @customized_concept.description %>
      </h4>

      <%= render 'customized_concepts/index', locals: {customized_concepts: @customized_concepts} %>
    </div>
  </div>



</div>

<!-- VIDEO MODAL -->


<div class="modal fade collect_video_modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <h3 class="modal-title" id="myModalLabel">收藏影片</h3>
      <div class="modal-body">
          <%= simple_form_for(@collect_video, url: collect_videos_path, method: "post") do |f| %>
            <%= f.input :user_id, as: :hidden%>
            <%= f.input :title, placeholder: '輸入此影片的名稱..' %>
            <%= f.input :url, input_html: { value: @customized_concept.video } %>
            <%= f.submit '保存', class: "btn btn-primary" %>
            <%= hidden_field_tag :customized_concept_id, @customized_concept.id %>
            <%= hidden_field_tag :course_id, @course.id %>
          <% end %>
      </div>
    </div>
  </div>
</div>

<!-- END VIDEO MODAL -->


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <% if @next_concept %>
          <h4 class="modal-title" id="myModalLabel">已通過自我挑戰 </h4>
          <div class="modal-body">
            <p></p>
          </div>
        <% else %>
          <h4 class="modal-title" id="myModalLabel">恭喜完成此課程所有觀念挑戰</h4>
        <% end %>
        
      </div>
      <div class="modal-body">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <% if @next_concept %>
          <button type="button" class="btn btn-default"><%= link_to("前往下一個觀念", course_customized_concept_path(@course, @next_concept))%></button>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-1.10.2.js"></script>

<script>  
  $(document).ready(function() {
    if($("#notice").html().indexOf("Successfully pass") >= 0) {
      $('#myModal').modal();
    }

    if($("#notice").html().indexOf("恭喜一次通過測驗") >= 0) {
      $('.modal-body p').text($('#notice').text());
      $('#myModal').modal();
    }

  });
</script>

app/views/customized_concepts/student_detail.html.erb
<div class="pb-index-wrapper pb-container">
  <div class="row">
    <% if @tests.count != 0 %>
      <%= render 'test_attemp_detail' %>
    <% else %>
      <!-- TEST_PAPER_DETAIL START -->
      <%= render 'test_paper_detail' %>
      <!-- TEST_PAPER_DETAIL END -->
    <% end %>
  </div>
</div>