config/routes.rb
Rails.application.routes.draw do
  
  
  resources :test_papers

  mount Ckeditor::Engine => '/ckeditor'
  resources :test_attempts

  resources :teachers do
    resources :groups
  end

  resources :courses do
    resources :customized_concepts
    get 'concept_map'
    get 'concept_list'
    get 'list_students'
    get 'reports'
    get 'course_filter', on: :collection
    get 'filter_by_level', on: :collection
    get 'change_status/:group_id', to: 'courses#change_status', as: 'change_status'
  end

  resources :collect_courses do
    get 'join_list/:course_id', to: 'collect_courses#join_list', as: 'join_list', on: :collection
    get 'join_group/:group_id', to: 'collect_courses#join_group', as: 'join_group'
  end

  resources :groups do
    resources :courses
    post 'add_student', on: :collection
  end

  resources :prototypes do
    get 'landing_page', on: :collection
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  

  authenticated :user do
    root to: "prototypes#index", as: :authenticated_root
  end
  unauthenticated do
    root to: "prototypes#landing_page", as: :unauthenticated_root
  end
  
  get '/courses/12/' => 'prototype#course', as: :course1
  get '/courses/13/' => 'prototype#course2', as: :course2
  get '/courses/14/' => 'prototype#course3', as: :course3
  get '/test/12/' => 'prototype#test', as: :test
  get '/test/13/' => 'prototype#test2', as: :test2
  get '/test/14/' => 'prototype#test3', as: :test3
  get '/test/15/' => 'prototype#special_test', as: :special_test
  get '/test/12/result' => 'prototype#result', as: :result
  get '/test/13/result' => 'prototype#result2', as: :result2
  get '/test/14/result' => 'prototype#result3', as: :result3
  get '/rank' => 'prototype#rank', as: :rank
  get '/mission_center' => 'prototype#mission_center', as: :mission_center
  get '/mission_danger' => 'prototype#mission_danger', as: :mission_danger
  

  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    # omniauth_callbacks: "users/omniauth_callbacks",
    # confirmations: "users/confirmations",
    # passwords: "users/passwords"
  }

  devise_scope :user do
    get 'users/student_new', to: 'users/registrations#student_new', :as => :new_student_registration
    get 'users/teacher_new', to: 'users/registrations#teacher_new', :as => :new_teacher_registration
    # get 'users/student_edit', to: 'users/registrations#student_edit', :as => :edit_student_registration
    # get 'users/teacher_edit', to: 'users/registrations#teacher_edit', :as => :edit_teacher_registration
  end

  resources :customized_concepts do
    resources :tests
    resources :test_attempts
    resources :test_papers
    resources :test_paper_questions
    get 'student_detail/:user_id', to: 'customized_concepts#student_detail', as: 'student_detail'
    get 'paper_option', on: :collection
  end

  resources :test_paper_questions do
    get 'test_preview'
  end

  get 'build_by_database/:customized_concept_id', to: 'test_paper_questions#build_by_database', as: 'build_by_database'
  get 'search_test', to: 'test_paper_questions#search_test', as: 'search_test'
  get 'add_test/:customized_concept_id/:test_paper_question_id', to: 'test_paper_questions#add_test', as: 'add_test'
  
  resources :personal_profiles

  resources :collect_videos
  # FOR THE CITY SELECT FORM IN THE SINGUP PAGE 
  mount TaiwanCity::Engine => '/taiwan_city'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :set_teacher, only: [:reports]

  # GET /courses
  # GET /courses.json
  def index
    @group = Group.find(params[:group_id])
    @courses = @group.courses

    @teacher = current_user.teacher
    @collect_courses = @teacher.collect_courses
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])
    @customized_concepts = @course.customized_concepts

    
    @group = Group.find(params[:group_id]) if params[:group_id]
  end

  # GET /courses/new
  def new
    @teacher = current_user.teacher
    @course = @teacher.courses.build
    @course.group_id = params[:group_id]

    @group = Group.find(params[:group_id])
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
    
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @group = @course.group
    @teacher = current_user.teacher
    
    respond_to do |format|
      if @course.save
        format.html { redirect_to teacher_group_path(@teacher, @group), notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    @group = Group.find(params[:course][:group_id])
    @teacher = current_user.teacher

    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to group_courses_path(@group), notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @group = @course.group
    @teacher = current_user.teacher
    @course.destroy
    respond_to do |format|
      format.html { redirect_to group_courses_path(@group), notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def concept_list
    @course = Course.find(params[:course_id])
    @group = Group.find(@course.group) 
    @customized_concepts = @course.customized_concepts
    respond_to do |format|
      format.js
    end  
  end

  def concept_map
    @course = Course.find(params[:course_id])
    @customized_concepts = @course.customized_concepts

    respond_to do |format|
      format.js
    end  
  end

  def list_students
    @course = Course.find(params[:course_id])
    @group = @course.group

    respond_to do |format|
      format.js
    end  
  end

  def reports
    @course = Course.find(params[:course_id])
    @concepts = @course.customized_concepts
    @group = @course.group
    @students = @group.students

    respond_to do |format|
      format.js
    end  
  end

  def course_filter
    @s_filter = params[:select_item][:subject_id]
    @v_filter = params[:select_volume][:volume_id]

    if @s_filter.count > 1 && @v_filter.count <= 1# user didn't select any subject, so return all of the courses
      @courses = Course.opened.where(subject_id: @s_filter).order(:title).page params[:page]
    elsif @s_filter.count <= 1 && @v_filter.count > 1
      @courses = Course.opened.where(volume_id: @v_filter).order(:title).page params[:page]
    else
      if @s_filter.count > 1 && @v_filter.count > 1
        @courses = Course.opened.where(subject_id: @s_filter, volume_id: @v_filter).order(:title).page params[:page]
      else
        @courses = Course.opened.order(:title).page params[:page]
      end
    end

    @target_courses = EducationLevel.all
    set_user
    respond_to do |format|
      format.html { render "prototypes/index" }
      format.js
    end  
  end

  def filter_by_level
    @target_courses = EducationLevel.all
    set_user

    @level = EducationLevel.find(params[:education_level_id])
    @subjects = @level.subjects
    @volumes = @level.volumes
    @courses = Course.opened.where(education_level_id: params[:education_level_id]).order(:title).page params[:page]

    respond_to do |format|
      format.html { render "prototypes/index" }
      format.js
    end
  end

  def change_status
    @course = Course.find(params[:course_id])

    @group = Group.find(params[:group_id])
    @courses = @group.courses

    @course.is_open = !@course.is_open #reverse is_open value

    if @course.save!
      respond_to do |format|
        format.html { redirect_to group_courses_path(@group) }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    def set_teacher
      @teacher = current_user.teacher
    end
    
    def set_user
      if user_signed_in?
        if current_user.has_role? :student
          @user = current_user.student
          @groups = @user.groups # To-Do : should modify the group which is student belongs to
        else
          @user = current_user.teacher
          @groups = @user.groups
          @subjects = Subject.all
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:education_level_id, :subject_id, :teacher_id, :title, :overview, :group_id, :volume_id, :image, :is_open, :build_teacher_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper

	# show test_attemp or test_paper last retry_time
	def show_retry_time(concept, user_id) 
    if !concept.test_attempts.where(user: user_id).last.nil? 
    	link_to customized_concept_student_detail_path(concept, user_id) do
    		content_tag(:div, concept.test_attempts.where(user: user_id).last.retry_time)
    	end
		elsif !concept.test_papers.where(user: user_id).last.nil?
			link_to customized_concept_student_detail_path(concept, user_id) do
				content_tag(:div, concept.test_papers.where(user: user_id).last.retry_time)
			end
		else
			0
		end
	end

  def join_group_button(courses, collect_course, group)
    
    if courses.where(title: collect_course.title, overview: collect_course.overview).count != 0
      link_to "已加入到此群組", collect_course_join_group_path(collect_course, @group), class: "btn btn-default disabled"
    else
      link_to "加入到此群組", collect_course_join_group_path(collect_course, group), class: "btn btn-default"
    end
  end

  def render_course_right_info(course, customized_concepts, group)
    if current_user.has_role? :student
      render  partial: "courses/list_customized_concept", locals: {customized_concepts: customized_concepts, group: group}
    else
      if current_user.teacher.id == course.teacher_id
        # TEACHER CAN EDIT, DELETE
        render  partial: "courses/course_concept_list", locals: {customized_concepts: customized_concepts, group: group}
      else
        # ONLY SHOW CONCEPT MAP
        render  partial: "courses/list_customized_concept", locals: {customized_concepts: customized_concepts, group: group}
      end
    end
  end

  def test_total_count(concept)
    if concept.test_paper_questions.first != nil
      concept.test_paper_questions.first.test_paper_options.count
    else
      concept.tests.count
    end
  end

  def build_test(concept, group, tests)
    if concept.test_paper_questions.first == nil
      link_to '建立考題', new_customized_concept_test_paper_question_path(concept, group: group), class: "btn btn-default"
    else
      link_to('移除考題', customized_concept_test_paper_question_path(concept, tests.last.id), method: :delete ,class: "btn btn-danger")
    end
  end

  def build_test_from_database(concept)
    if concept.test_paper_questions.first == nil
      link_to '題庫出題', build_by_database_path(concept), class: "btn btn-default"
    end
  end


end

app/views/courses/_course_back_link.html.erb
<% if current_user.has_role? :student %>
  <% if @group%>
    <%=link_to teacher_group_path(@group.teacher_id, @group) do %> 
      <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> 群組首頁
    <% end %>
  <% else %>
    <%=link_to prototypes_path do %> 
      <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> 學生首頁
    <% end %>
  <% end %>
<!-- Teacher Back Link-->
<% else %> 
  <% if @group%>
    <%=link_to teacher_group_path(@group.teacher_id, @group) do %> 
      <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> 群組首頁
    <% end %>
  <% else %>
    <%=link_to prototypes_path do %> 
      <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> 教師首頁
    <% end %>
  <% end %>
<% end %>

app/views/courses/_course_concept_list.html.erb
<%= link_to("新增觀念", new_course_customized_concept_path(@course), 'data-toggle' => "modal", 'data-target' => "#myModal", class: "btn btn-primary", remote: true) %>
<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>名稱</th>
			<th>觀念描述</th>
			<th>講義 </th>
			<th>考題數量 </th>
      <th colspan="2"> 出題方式</th>
      <th>點數</th>
      <th> 觀念編輯 </th>
		</tr>
	</thead>

	<tbody>
		<% @customized_concepts.each do |customized_concept| %>
			<tr>
				<td><%= customized_concept.title %></td>
				<td><%= customized_concept.description %></td>
				<td><%= link_to("顯示講義", customized_concept.lecture.url) if customized_concept.lecture.url != nil%></td>
				<td><%= test_total_count(customized_concept) %></td>
        <td><%= build_test(customized_concept, @group, customized_concept.test_paper_questions) %></td>
        <td><%= build_test_from_database(customized_concept) %> </td>
        <td><%= customized_concept.point %></td>
        <td>
          <%= link_to edit_course_customized_concept_path(customized_concept.course_id, customized_concept), 'data-toggle' => "modal", 'data-target' => "#myModal", class: "btn btn-default", remote: true do %>
            <i class="fa fa-pencil"></i>
          <% end %>
        </td>
				<td>
          <%= link_to course_customized_concept_path(customized_concept.course_id, customized_concept), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
          <i class="fa fa-trash-o"></i>
          <% end %>
        </td>
			</tr>
		<% end %>
	</tbody>
</table>


<!-- Concept new form Modal -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">建立新觀念</h4>
      </div>
      <div class="modal-body">
        <div class="concept-new-form">
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/courses/_course_concept_map.html.erb
<h3> 觀念地圖 </h3>
<% if @group%>
  <%= render  partial: "courses/list_customized_concept", locals: {customized_concepts: @customized_concepts, group: @group} %>
<% else %>
  <%= render partial: 'courses/list_customized_concept', locals: {customized_concepts: @customized_concepts} %>
<% end %>
<div class="course-info-display">
  <h1> </h1>
</div>

app/views/courses/_course_left_bar.html.erb
<div class="list-group">
  <% if current_user.has_role? :teacher %>
		<% if current_user.teacher.id == @course.teacher_id %>
			<%= link_to("觀念地圖", course_concept_map_path(@course), remote: true, class: "list-group-item") %>
			<%= link_to("觀念編輯", course_concept_list_path(@course), remote: true, class: "list-group-item") %>
			<%= link_to("學生", course_list_students_path(@course), remote: true, class: "list-group-item") %>
			<%= link_to("Report", course_reports_path(@course), remote: true, class: "list-group-item") %>
		<% end %>
  <% end  %>

</div>

app/views/courses/_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= simple_form_for(@course) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :group_id, as: :hidden %>
        <%= f.input :teacher_id, as: :hidden %>
        <%= f.input :education_level_id do%>
          <%= f.select :education_level_id, EducationLevel.all.map { |r| [r.title, r.id, { class: r.id }] } %>
        <% end %>

        <!-- TO - DO : modify volume into EducationLevel.volume, it should disply by dynamic form  -->
        <%= f.input :volume_id do %> 
          <%= f.select :volume_id, Volume.where(education_level_id: 2).all.map { |r| [r.title, r.number] } %>
        <% end %>

        <%= f.input :subject_id do %>
          <%= f.select :subject_id, Subject.all.map { |s| [s.title, s.id, { class: s.id }] } %>
        <% end %>

        <%= f.input :is_open, label: "是否開放課程" do %>
          <%= f.select(:is_open, options_for_select([['不開放', false], ['開放', true]])) %>
        <% end %>

        <%= f.input :image, as: :file, label: '課程圖片'%>
        <%= f.input :title, label: '課程名稱'%>
        <%= f.input :overview, label: '課程描述'%>
      </div>

      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    <% end %>


  </div>
</div>

app/views/courses/_subject_result.html.erb
<li class="list-group-item list-group-item-warning"><strong>科目</strong></li>
  <%= form_tag(course_filter_courses_path, method: "get", remote: true, class: "subject-list-form") do %>
    <%= collection_check_boxes(:select_volume, :volume_id, @volumes.all, :number, :title) do |b|%>
      <%= b.label(class: "list-group-item") { b.check_box + b.text } %>
    <% end %>

    <%= collection_check_boxes(:select_item, :subject_id, @subjects.all, :id, :title) do |b|%>
      <%= b.label(class: "list-group-item") { b.check_box + b.text } %>
    <% end %>
    <%= submit_tag("送出", :style => "display:none") %>
  <% end %>

<script type="text/javascript">  
  $(function(){
   $("input[name='select_item[subject_id][]']").on('change',function(){
       $( ".subject-list-form" ).submit();
      });
   $("input[name='select_volume[volume_id][]']").on('change',function(){
       $( ".subject-list-form" ).submit();
      });
  });
</script>

app/views/courses/concept_list.js.erb
$('.course-info-display').html('<%= escape_javascript render "course_concept_list" %>');

app/views/courses/concept_map.js.erb
$('.course-info-display').html('<%= escape_javascript render "course_concept_map" %>');

app/views/courses/edit.html.erb
<div class="pb-index-wrapper pb-container">
<h1>Editing Course</h1>

  <%= render 'form' %>
  
</div>

app/views/courses/filter_by_level.js.erb
$('.subject-list').html('<%= escape_javascript render "subject_result" %>');
$('.list-course').html('<%= escape_javascript render "course_filter_result" %>');

app/views/courses/list_students.js.erb
$('.course-info-display').html('<%= escape_javascript render "course_list_student" %>');

app/views/courses/new.html.erb
<div class="pb-index-wrapper pb-container">
  <!-- Back Link -->
  <div class="row">
    <div class="col-md-2">
      <%= link_to teacher_group_path(@teacher, @group) do %>
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> 群組首頁
      <% end %>
    </div>
  </div>
  <!-- End Back Link -->

  <div class="col-md-offset-5 col-md-4">
    <h1>建立群組課程</h1>
  </div>

  <%= render 'form' %>

</div>

app/views/courses/reports.js.erb
$('.course-info-display').html('<%= escape_javascript render "course_reports" %>');

app/views/courses/show.html.erb
<div class="pb-index-wrapper pb-container">
  <p id="notice"><%= notice %></p>
  <%= render "course_back_link" %>
  <!-- End Teacher Back Link -->

  <div class="row">
    <div class="col-md-8">
      <h2>
        <%= @course.title %>
      </h2>
    </div>
  </div>

  <h4>
    <strong>Overview:</strong>
    <%= @course.overview %>
  </h4>

  <p>
    <strong>Teacher:</strong>
    <%= @course.teacher_id %>
  </p>


  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <%= render 'course_left_bar' %>
      </div>
    </div>
    <div class="col-md-9">
      <div class="course-info-display">
        <% if @group%>
          <%= render_course_right_info(@course, @customized_concepts, @group) %>
        <% else %>
          <%= render_course_right_info(@course, @customized_concepts, @group) %>
        <% end %>
      </div>
    </div>

    
  </div>


</div>